USE [master]
GO
/****** Object:  Database [QLCHBanSach]    Script Date: 1/1/2022 9:29:01 PM ******/
CREATE DATABASE [QLCHBanSach]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLCHBanSach', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QLCHBanSach.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLCHBanSach_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QLCHBanSach_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [QLCHBanSach] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLCHBanSach].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLCHBanSach] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLCHBanSach] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLCHBanSach] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLCHBanSach] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLCHBanSach] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLCHBanSach] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QLCHBanSach] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLCHBanSach] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLCHBanSach] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLCHBanSach] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLCHBanSach] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLCHBanSach] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLCHBanSach] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLCHBanSach] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLCHBanSach] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QLCHBanSach] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLCHBanSach] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLCHBanSach] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLCHBanSach] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLCHBanSach] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLCHBanSach] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLCHBanSach] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLCHBanSach] SET RECOVERY FULL 
GO
ALTER DATABASE [QLCHBanSach] SET  MULTI_USER 
GO
ALTER DATABASE [QLCHBanSach] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLCHBanSach] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLCHBanSach] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLCHBanSach] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QLCHBanSach] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QLCHBanSach] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'QLCHBanSach', N'ON'
GO
ALTER DATABASE [QLCHBanSach] SET QUERY_STORE = OFF
GO
USE [QLCHBanSach]
GO
/****** Object:  Table [dbo].[CHITIETDATSACH]    Script Date: 1/1/2022 9:29:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETDATSACH](
	[MaHoaDon] [int] NOT NULL,
	[MaSach] [int] NOT NULL,
	[GiaBan] [money] NOT NULL,
	[SoLuong] [int] NULL,
	[MucGiamGia] [int] NULL,
 CONSTRAINT [PK_CHITIETDATSACH] PRIMARY KEY CLUSTERED 
(
	[MaHoaDon] ASC,
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DONDATSACH]    Script Date: 1/1/2022 9:29:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DONDATSACH](
	[MaHoaDon] [int] identity(1,1) NOT NULL,
	[MaKH] [int] NOT NULL,
	[MaNV] [int] NOT NULL,
	[NgayDat] [date] NULL,
	[NgayChuyen] [date] NULL,
	[NgayGiao] [date] NULL,
	[NoiGiao] [nvarchar](255) NULL,
 CONSTRAINT [PK_DONDATSACH] PRIMARY KEY CLUSTERED 
(
	[MaHoaDon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 1/1/2022 9:29:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MaKH] [int] identity(1,1) NOT NULL,
	[HoTenKH] [nvarchar](255) NULL,
	[DiaChi] [nvarchar](255) NULL,
	[DienThoai] [nvarchar](11) NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 1/1/2022 9:29:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MaNV] [int] identity(1,1) NOT NULL,
	[HoTenNV] [int] NULL,
	[NgaySinh] [date] NULL,
	[DiaChi] [nvarchar](255) NOT NULL,
	[DienThoai] [nvarchar](11) NULL,
	[NgayLamViec] [nchar](10) NULL,
	[Luong] [money] NULL,
	[PhuCap] [money] NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MaNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHAXUATBAN]    Script Date: 1/1/2022 9:29:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHAXUATBAN](
	[MaNXB] [int] identity(1,1) NOT NULL,
	[TenNXB] [nvarchar](255) NULL,
 CONSTRAINT [PK_NHAXUATBAN] PRIMARY KEY CLUSTERED 
(
	[MaNXB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SACH]    Script Date: 1/1/2022 9:29:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SACH](
	[MaSach] [int] identity(1,1) NOT NULL,
	[TenSach] [nvarchar](255) NULL,
	[MaTheLoai] [int] NOT NULL,
	[MaNXB] [int] NOT NULL,
	[MaTacGia] [int] NOT NULL,
	[NgayXB] [date] NULL,
	[GiaSach] [money] NULL,
	[SoLuong] [int] NULL,
 CONSTRAINT [PK_SACH] PRIMARY KEY CLUSTERED 
(
	[MaSach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TACGIA]    Script Date: 1/1/2022 9:29:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TACGIA](
	[MaTacGia] [int] identity(1,1) NOT NULL,
	[TenTacGia] [nvarchar](255) NULL,
 CONSTRAINT [PK_TACGIA] PRIMARY KEY CLUSTERED 
(
	[MaTacGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THELOAISACH]    Script Date: 1/1/2022 9:29:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THELOAISACH](
	[MaTheLoai] [int] identity(1,1) NOT NULL,
	[TenTheLoai] [nvarchar](255) NULL,
 CONSTRAINT [PK_THELOAISACH] PRIMARY KEY CLUSTERED 
(
	[MaTheLoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHITIETDATSACH]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETDATSACH_DONDATSACH] FOREIGN KEY([MaHoaDon])
REFERENCES [dbo].[DONDATSACH] ([MaHoaDon])
GO
ALTER TABLE [dbo].[CHITIETDATSACH] CHECK CONSTRAINT [FK_CHITIETDATSACH_DONDATSACH]
GO
ALTER TABLE [dbo].[CHITIETDATSACH]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETDATSACH_SACH] FOREIGN KEY([MaSach])
REFERENCES [dbo].[SACH] ([MaSach])
GO
ALTER TABLE [dbo].[CHITIETDATSACH] CHECK CONSTRAINT [FK_CHITIETDATSACH_SACH]
GO
ALTER TABLE [dbo].[DONDATSACH]  WITH CHECK ADD  CONSTRAINT [FK_DONDATSACH_KHACHHANG] FOREIGN KEY([MaKH])
REFERENCES [dbo].[KHACHHANG] ([MaKH])
GO
ALTER TABLE [dbo].[DONDATSACH] CHECK CONSTRAINT [FK_DONDATSACH_KHACHHANG]
GO
ALTER TABLE [dbo].[DONDATSACH]  WITH CHECK ADD  CONSTRAINT [FK_DONDATSACH_NHANVIEN] FOREIGN KEY([MaNV])
REFERENCES [dbo].[NHANVIEN] ([MaNV])
GO
ALTER TABLE [dbo].[DONDATSACH] CHECK CONSTRAINT [FK_DONDATSACH_NHANVIEN]
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_NHAXUATBAN] FOREIGN KEY([MaNXB])
REFERENCES [dbo].[NHAXUATBAN] ([MaNXB])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_NHAXUATBAN]
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_TACGIA] FOREIGN KEY([MaTacGia])
REFERENCES [dbo].[TACGIA] ([MaTacGia])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_TACGIA]
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_THELOAISACH] FOREIGN KEY([MaTheLoai])
REFERENCES [dbo].[THELOAISACH] ([MaTheLoai])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_THELOAISACH]
GO
USE [master]
GO
ALTER DATABASE [QLCHBanSach] SET  READ_WRITE 
GO
